export type CharacterName =
  | 'Aino'
  | 'Albedo'
  | 'Alhaitham'
  | 'Aloy'
  | 'Amber'
  | 'Arataki Itto'
  | 'Arlecchino'
  | 'Baizhu'
  | 'Barbara'
  | 'Beidou'
  | 'Bennett'
  | 'Candace'
  | 'Charlotte'
  | 'Chasca'
  | 'Chevreuse'
  | 'Chiori'
  | 'Chongyun'
  | 'Citlali'
  | 'Clorinde'
  | 'Collei'
  | 'Cyno'
  | 'Dahlia'
  | 'Dehya'
  | 'Diluc'
  | 'Diona'
  | 'Dori'
  | 'Emilie'
  | 'Escoffier'
  | 'Eula'
  | 'Faruzan'
  | 'Fischl'
  | 'Flins'
  | 'Freminet'
  | 'Furina'
  | 'Gaming'
  | 'Ganyu'
  | 'Gorou'
  | 'Hu Tao'
  | 'Iansan'
  | 'Ifa'
  | 'Ineffa'
  | 'Jean'
  | 'Kachina'
  | 'Kaedehara Kazuha'
  | 'Kaeya'
  | 'Kamisato Ayaka'
  | 'Kamisato Ayato'
  | 'Kaveh'
  | 'Keqing'
  | 'Kinich'
  | 'Kirara'
  | 'Klee'
  | 'Kujou Sara'
  | 'Kuki Shinobu'
  | 'Lan Yan'
  | 'Lauma'
  | 'Layla'
  | 'Lisa'
  | 'Lynette'
  | 'Lyney'
  | 'Mavuika'
  | 'Mika'
  | 'Mona'
  | 'Mualani'
  | 'Nahida'
  | 'Navia'
  | 'Neuvillette'
  | 'Nilou'
  | 'Ningguang'
  | 'Noelle'
  | 'Ororon'
  | 'Qiqi'
  | 'Raiden Shogun'
  | 'Razor'
  | 'Rosaria'
  | 'Sangonomiya Kokomi'
  | 'Sayu'
  | 'Sethos'
  | 'Shenhe'
  | 'Shikanoin Heizou'
  | 'Sigewinne'
  | 'Skirk'
  | 'Sucrose'
  | 'Tartaglia'
  | 'Thoma'
  | 'Tighnari'
  | 'Traveler'
  | 'Varesa'
  | 'Venti'
  | 'Wanderer'
  | 'Wriothesley'
  | 'Xiangling'
  | 'Xianyun'
  | 'Xiao'
  | 'Xilonen'
  | 'Xingqiu'
  | 'Xinyan'
  | 'Yae Miko'
  | 'Yanfei'
  | 'Yaoyao'
  | 'Yelan'
  | 'Yoimiya'
  | 'Yumemizuki Mizuki'
  | 'Yun Jin'
  | 'Zhongli'

export interface CharacterProps {
  name: string
  element: string
  level: number
  actived_constellation_num: number
}
export type ElementType = 'Pyro' | 'Hydro' | 'Electro' | 'Cryo' | 'Anemo' | 'Dendro' | 'Geo'
export type WeaponType = 'Sword' | 'Claymore' | 'Bow' | 'Polearm' | 'Catalyst'
export interface ImaginariumDataType {
  elements: [ElementType, ElementType, ElementType]
  starting_characters: CharacterName[]
  special_characters: CharacterName[]
}
export interface PresetDataType extends ImaginariumDataType {
  name: string
  year: number
  month: number
}
